# Generated by Django 3.0.1 on 2020-01-07 16:39

from django.db import migrations, models
import payment_requests.models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_requests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrequest',
            name='ceo',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO'), ('OH', 'ON_HOLD'), ('CNC', 'CANCELLED')], max_length=10),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='payment_metod',
            field=models.CharField(choices=[('MN', 'MANUAL'), ('AU', 'AUTO'), ('SA', 'SEMAUTO')], default=payment_requests.models.PaymentMethod['MANUAL'], max_length=2),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='payment_system',
            field=models.CharField(choices=[('PB', 'PRIVAT'), ('PP', 'PAYPAL'), ('BA', 'BANK_ACCOUNT'), ('PO', 'PAYONEER'), ('CC', 'CREDIT_CARD'), ('CH', 'CASH'), ('BC', 'BY_CHOICE')], max_length=2),
        ),
    ]
