# Generated by Django 3.0.1 on 2020-01-07 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_requests', '0002_auto_20200107_1839'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentrequest',
            options={'ordering': ['id']},
        ),
    ]
