# Generated by Django 3.0.1 on 2020-01-08 20:53

from django.db import migrations, models
import payment_requests.utils


class Migration(migrations.Migration):

    dependencies = [
        ('payment_requests', '0003_auto_20200107_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrequest',
            name='currency',
            field=models.CharField(choices=[('UAH', 'UAH'), ('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('RUB', 'RUB'), ('CAD', 'CAD'), ('PLN', 'PLN'), ('CZK', 'CZK')], max_length=3, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='department',
            field=models.CharField(max_length=10, verbose_name='Deprt-nt'),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='fact_payment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fact'),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='form_w8ben_w9',
            field=models.CharField(blank=True, max_length=250, verbose_name='FormW8'),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='payment_details',
            field=models.CharField(blank=True, max_length=999, verbose_name='Details'),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='payment_metod',
            field=models.CharField(choices=[('MN', 'MANUAL'), ('AU', 'AUTO'), ('SA', 'SEMAUTO')], default=payment_requests.utils.PaymentMethod['MANUAL'], max_length=2, verbose_name='PayMethod'),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='payment_system',
            field=models.CharField(choices=[('PB', 'PRIVAT'), ('PP', 'PAYPAL'), ('BA', 'BANK_ACCOUNT'), ('PO', 'PAYONEER'), ('CC', 'CREDIT_CARD'), ('CH', 'CASH'), ('BC', 'BY_CHOICE')], max_length=2, verbose_name='PaySystem'),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='planned_payment_date',
            field=models.DateField(verbose_name='Plan'),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='recipient',
            field=models.CharField(max_length=250, verbose_name='Recep.'),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='request_date',
            field=models.DateField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='requisits',
            field=models.CharField(max_length=999, verbose_name='Requsits'),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='subdivision',
            field=models.CharField(max_length=250, verbose_name='Division'),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='user',
            field=models.CharField(max_length=250, verbose_name='User'),
        ),
    ]
